version: 2.1

orbs:
  maven: circleci/maven@1.1.0

workflows:
  maven_test:
    jobs:
      - maven/test:
          test_results_path: libslparser-tests/target/surefire-reports
          executor:
            tag: "8.0"
